blank_issues_enabled: false

contact_links:
  - name: GaeaExplorer community channels
    url: https://gaeaway.com/community
    about: Please ask for technical support on one of the other community channels, not here.
